config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'events/create'
  get 'events/index'
  get 'events/show'
  root to: "profiles#edit"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events, only: [:index]

  resources :workouts, only: %i[index show create delete] do
    member do
      get 'overview'
      get 'description'
      get 'summary'
      post 'complete'
      patch 'start'
      patch 'freestyle_start'
      get 'freestyle'
      post 'add_exercise'
      delete 'remove_exercise'
    end
  end

  resources :workout_exercises, only: %i[show create] do
    member do
      post 'next_set'
      patch 'stop'
      patch 'update_last_time'
      get 'freestyle_show'
    end
  end

  resources :exercises, only: [:index, :show]

  resource :profile, only: %i[edit update show] do
    member do
    end
  end
  resources :group_classes, only: [:show]
  get 'home', to: 'pages#home', as: 'home'
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user

  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises

  validates :start_time, presence: true
  validates :end_time, presence: true

  
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: [:show, :overview, :start, :description, :summary, :freestyle, :add_exercise, :remove_exercise]
  before_action :store_previous_path, only: [:show, :overview]

  def freestyle
    @exercises = Exercise.all
    @in_freestyle_mode = params[:from_freestyle].present?
  end

  def add_exercise
    @selected_exercise = Exercise.find_by(id: params[:exercise_id]) if params[:exercise_id]

    @workout_exercise = @workout.workout_exercises.build(
      exercise: @selected_exercise,
      set: @selected_exercise.workout_exercises.first.set,
      kg: @selected_exercise.workout_exercises.first.kg,
      volume: @selected_exercise.workout_exercises.first.volume,
      time: @selected_exercise.workout_exercises.first.time,
      calories: @selected_exercise.workout_exercises.first.calories
    )

    if @workout_exercise.save
      redirect_to workout_path(@workout, from_freestyle: params[:from_freestyle]), notice: 'Exercise added successfully!💪'
    else
      render :freestyle, alert: 'Failed to add exercise. :('
    end
  end

  def remove_exercise
    @workout_exercise = @workout.workout_exercises.find_by(exercise_id: params[:exercise_id])
    if @workout_exercise&.destroy
      redirect_to workout_path(@workout, from_freestyle: params[:from_freestyle]), notice: 'Exercise removed successfully! :D'
    else
      redirect_to workout_path(@workout, from_freestyle: params[:from_freestyle]), alert: 'Failed to remove exercise.'
    end
  end

  def show
    @workout = Workout.find(params[:id])
    @workout_exercises = @workout.workout_exercises
    @muscle_groups = @workout_exercises.map { |workout_exercise| workout_exercise.exercise.muscle_group }.uniq

    @in_freestyle_mode = params[:from_freestyle].present?
  end

  def update
    @workout = Workout.find(params[:id])
    if @workout.update(workout_params)
      redirect_to workout_path(@workout, from_freestyle: params[:from_freestyle])
    else
      render :edit
    end
  end

  def overview
    @workout = Workout.find(params[:id])
    @exercises = @workout.exercises.includes(:exercise_category)
    @duration = (@workout.end_time - @workout.start_time) / 60 # in minutes
    @workout_exercise = @workout.workout_exercises.first
  end

  def start
    @workout = Workout.find(params[:id])
    @workout_exercise = @workout.workout_exercises.first
    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_or_create_by(date: Date.today)
    @day_summary.update(start_time: Time.current, calories_burnt: 0, end_time: nil, last_update_time: nil)
    redirect_to workout_exercise_path(@workout_exercise)
  end

  def freestyle_start
    @workout = Workout.all[4]
    @free_workout_exercises = @workout.workout_exercises
    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_or_create_by(date: Date.today)
    @day_summary.update(start_time: Time.current, calories_burnt: 0, end_time: nil, last_update_time: nil)
    redirect_to freestyle_show_workout_exercise_path(@free_workout_exercises.first)
  end

  def description
    @workout = Workout.find(params[:id])
    @workout_exercises = @workout.workout_exercises
    @workout_exercise = @workout_exercises.first
    @in_freestyle_mode = params[:from_freestyle].present?
  end

  def summary
    @workout = Workout.find(params[:id])
    @exercises = @workout.exercises

    @duration = (@workout.end_time - @workout.start_time) / 60 # in minutes
    @summary_today = current_user.profile.day_summaries.find_by(date: Date.today)
    @end_time_today = @summary_today.end_time
    @start_time_today = @summary_today.start_time
    @duration_today = ((@end_time_today - @start_time_today)/ 60).to_i
    @calories_burnt_today = @summary_today.calories_burnt.round(2)
    @total_kg_lifted = @exercises.sum(:kg)
    @summary_today.kg ||= 0
    @summary_today.kg += @total_kg_lifted
    @summary_today.save
    @pr_count = 0

    @exercise_detail = @exercises.map do |exercise|
      workout_exercise = WorkoutExercise.find_by(exercise: exercise, workout: @workout)
      pr = check_pr(exercise, workout_exercise.kg, @workout.user)
      @pr_count += 1 if pr == 'PR'

      {
        name: exercise.name,
        volume: workout_exercise.volume * workout_exercise.set,
        weight: workout_exercise.kg,
        pr: pr
      }
    end

    current_user.profile.add_workout_xp(@total_kg_lifted, @duration_today)

    @calories_burnt = calculate_calories_burnt(@workout.workout_exercises)
  end

  private

  def set_workout
    @workout = Workout.find(params[:id])
  end

  def workout_params
    params.require(:workout).permit(:name, :workout_type, :user_id, :start_time, :end_time)
  end

  def calculate_calories_burnt(workout_exercises)
    profile = current_user.profile
    age = profile.age
    height = profile.height # in cm
    user_weight = profile.weight # in kg
    gender = profile.gender
    duration = @duration # in minutes

    bmr = if gender == 'male'
            10 * user_weight + 6.25 * height - 5 * age + 5
          else
            10 * user_weight + 6.25 * height - 5 * age - 161
          end

    met_values = {
      'running' => 9.8,
      'cycling' => 7.5,
      'swimming' => 8.0,
      'weightlifting' => 3.0
    }

    total_calories_burnt = workout_exercises.sum do |workout_exercise|
      met_value = workout_exercise.exercise.met_value
      exercise_weight = workout_exercise.kg
      duration_in_hours = duration / 60.0
      calories_burnt = (met_value * exercise_weight * duration_in_hours / 10)
      calories_burnt
    end

    total_calories_burnt
  end

  def check_pr(exercise, current_weight, user)
    max_weight = WorkoutExercise.joins(:workout)
                                .where(workouts: { user: user }, exercise: exercise)
                                .maximum(:kg)
    current_weight > max_weight ? 'PR' : nil
  end

  def store_previous_path
    session[:previous_path] = request.referer
  end
end

app/views/workouts/description.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <title>Workout Page</title>
</head>
<body>
    <div class="center-content">
        <div class="header-image">
            <img src="https://img.freepik.com/free-photo/smiley-woman-gym-outfit-enjoying-music-headphones_23-2148398814.jpg?uid=R156501570&ga=GA1.1.2040644916.1721225651" alt="Gym Image">
        </div>

        <div class="content">
            <h1>Today is <%= @workout.name %> day</h1>
            <ul class="workout-exercises-list">
                <% @workout_exercises.each do |workout_exercise| %>
                <li class="workout-exercise-item">
                    <div class="card-workouts">
                        <div class="exercise-image-box">
                          <img class="exercise-image" src="<%= workout_exercise.exercise.image_url %>" alt="<%= workout_exercise.exercise.name %>">
                        </div>
                        <div class="exercise-details d-flex flex-column justify-content-between">
                            <div class="exercise-name-box">
                              <h2 class="exercise-name"><%= workout_exercise.exercise.name %></h2>
                            </div>
                            <div class="exercise-info-box">
                              <p class="exercise-instruction"><%= workout_exercise.exercise.description %></p>
                              <p class="exercise-sets">🔁 <%= workout_exercise.set %> sets,  <%= workout_exercise.volume %> volumes</p>
                            </div>
                        </div>
                    </div>
                </li>
                <% end %>
            </ul>

            <div class="button-container">
                <% if params[:from_freestyle] == 'true' %>
                    <%= link_to "Back to Freestyle", workout_path(@workout, from_freestyle: 'true'), class: "btn btn-primary-custom" %>
                <% else %>
                    <%= link_to "Back", overview_workout_path(@workout), class: "btn btn-primary-custom-description" %>
                <% end %>
                <%= button_to "Start Workout", start_workout_path(@workout), method: :patch, class: "btn btn-success-custom-description" %>
            </div>
        </div>
    </div>
</body>
</html>

app/views/workouts/freestyle.html.erb
<%= form_with url: add_exercise_workout_path(@workout, from_freestyle: params[:from_freestyle]), method: :post, local: true, html: { class: 'freestyle-workout-form' } do |form| %>
  <%= hidden_field_tag :from_freestyle, params[:from_freestyle] || 'false' %>
<h2>💪</h2>
<h1 class= "add-exercise-title"> Add a exercise!</h1>
<div class= "form-group-box">
  <div class="form-group">
    <%= form.label :exercise_id, 'Exercise:', class: 'form-label' %>
    <%= form.collection_select :exercise_id, Exercise.all, :id, :name %>
  </div>

  <div class="form-group">
    <%= form.label :kg, 'Weight (kg):', class: 'form-label' %>
    <%= form.number_field :kg %>
  </div>

  <div class="form-group">
    <%= form.label :volume, 'Volume:', class: 'form-label' %>
    <%= form.number_field :volume %>
  </div>

  <% if @selected_exercise %>
    <div>
      <label>Time: <%= @selected_exercise.workout_exercises.first.time.strftime("%M").to_i %></label>
      <%= form.hidden_field :time, value: @selected_exercise.workout_exercises.first.time %>
    </div>
    <div>
      <label>Calories: <%= @selected_exercise.workout_exercises.first.calories %></label>
      <%= form.hidden_field :calories, value: @selected_exercise.workout_exercises.first.calories %>
    </div>
  <% end %>

  <div class="buttons">
    <%= link_to "Back to Workout", workout_path(@workout, from_freestyle: params[:from_freestyle]), class: "btn btn-back" %>
    <%= form.submit 'Add Exercise', class: "btn btn-primary" %>
  </div>
  </div>
<% end %>

app/views/workouts/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'Freestyle Workout', freestyle_workout_path(current_user.workouts.create(start_time: Time.now, end_time: Time.now + 1.hour)), class: 'button' %>
<% end %>

app/views/workouts/overview.html.erb
<div class="center-content">
  <h1>Today is <%= @workout.name %> day</h1>

  <%= image_tag "#{@workout.name.downcase}.png" %>

  <div>
    <p><strong>Activated muscles:</strong> <%= @workout.muscle_group %></p>
    <p>⏰ <%= @duration %> minutes</p>
  </div>

  <div class="button-container">
    <%= link_to "Program Guide", description_workout_path(@workout), class: "btn btn-primary-custom-description" %>
    <%#= link_to "Start Workout", workout_exercise_path(@workout_exercise), class: "btn btn-success-custom" %>
    <%= button_to 'Start Workout', start_workout_path(@workout), method: :patch, class: "btn btn-success-custom-description" %>
  </div>
</div>

app/views/workouts/show.html.erb
<div class="center-content">
  <div class="workout-show-container">
    <h1>Today is <br> <%= @workout.name %> day</h1>
    <%= image_tag "#{@workout.name.downcase}.png" %>
    <% if @workout.workout_exercises.any? %>
      <ul class="exercise-list">
        <% @workout.workout_exercises.each do |workout_exercise| %>
          <li class="exercise-item">
            <div class="exercise-info">
              <span class="exercise-name"><%= workout_exercise.exercise.name %></span>
              <span class="exercise-details">Weight: <%= workout_exercise.kg %> kg, Volume: <%= workout_exercise.volume %></span>
            </div>
            <%= button_to remove_exercise_workout_path(@workout, exercise_id: workout_exercise.exercise_id, from_freestyle: params[:from_freestyle]), method: :delete, class: "btn btn-danger-custom", data: { confirm: 'Are you sure you want to remove this exercise?' } do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No exercises added yet.</p>
    <% end %>

    <%= link_to 'Add Exercises', freestyle_workout_path(@workout), class: "btn btn-add-exercise", style: "margin-bottom: 30px; margin-top: 20px;" %>

    <div class="button-container" id="exercise_list">
      <% if @in_freestyle_mode %>
        <%= link_to "See List of Exercises", description_workout_path(@workout, from_freestyle: true), class: "btn freestyle-btn-primary-custom" %>
      <% else %>
        <%= link_to "See List of Exercises", description_workout_path(@workout, from_freestyle: true), class: "btn freestyle-btn-primary-custom" %>
      <% end %>
      <%= button_to 'Start Workout', freestyle_start_workout_path(@workout), method: :patch, class: "btn freestyle-btn-success-custom" %>
    </div>
  </div>
</div>

app/views/workouts/summary.html.erb
<div class="workout_summary">

  <h1>Awesome!</h1>

  <div class="card">
    <p>Total Time:</p>
    <p><%= @duration_today %> minutes</p>
  </div>
  <div class="card">
    <p>Total Volume:</p>
    <p><%= @total_kg_lifted %> KG</p>
  </div>
  <div class="card">
    <p>Total Calories Burnt:</p>
    <p><%= @calories_burnt_today %> kcal</p>
  </div>
  <div class="card">
    <p>PRs:</p>
    <p><%= @pr_count %></p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Exercise</th>
        <th>Volume</th>
      </tr>
    </thead>
    <tbody>
      <% @exercise_detail.each do |exercise| %>
      <% current_user.add_pushups(exercise[:volume]) if exercise[:name] == "Push-up" %>
      <% current_user.add_squats(exercise[:volume]) if exercise[:name] == "Squat" %>
      <% current_user.add_pullups(exercise[:volume]) if exercise[:name] == "Pull-up" %>
        <tr>
          <td><%= exercise[:name] %></td>
          <td><%= exercise[:volume] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>