config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'events/create'
  get 'events/index'
  get 'events/show'
  root to: "profiles#edit"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events, only: [:index]

  resources :workouts, only: %i[index show create delete] do
    member do
      get 'overview'
      get 'description'
      get 'summary'
      post 'complete'
      patch 'start'
      patch 'freestyle_start'
      get 'freestyle'
      post 'add_exercise'
      delete 'remove_exercise'
    end
  end

  resources :workout_exercises, only: %i[show create] do
    member do
      post 'next_set'
      patch 'stop'
      patch 'update_last_time'
      get 'freestyle_show'
    end
  end

  resources :exercises, only: [:index, :show]

  resource :profile, only: %i[edit update show] do
    member do
    end
  end
  resources :group_classes, only: [:show]
  get 'home', to: 'pages#home', as: 'home'
end

app/controllers/workout_exercises_controller.rb
class WorkoutExercisesController < ApplicationController
  before_action :set_workout_exercise, only: [:show, :stop, :update_last_time]

  def show
    #@workout_exercise = WorkoutExercise.find(params[:id])
    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_or_create_by(date: Date.today)
    @total_calories = @workout_exercise.calories
    @duration = @workout_exercise.time.strftime("%M").to_f
    @calories_burnt_per_second = (@total_calories / @duration) / 60

    @day_summary.calories_burnt = 0 if @current_index == 0

    @current_workout_exercises = @workout_exercise.workout.workout_exercises
    @current_index = @current_workout_exercises.find_index(@workout_exercise)
    @current_exercise = @current_workout_exercises[@current_index].exercise
    @max_index = @current_workout_exercises.count - 1

    @total_calories_burnt = @day_summary.calories_burnt
  end

  def freestyle_show
    @workout = Workout.all[4]
    @workout_exercise = WorkoutExercise.find(params[:id])

    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_or_create_by(date: Date.today)
    @total_calories = @workout_exercise.calories
    @duration = @workout_exercise.time.strftime("%M").to_f
    @calories_burnt_per_second = (@total_calories / @duration) / 60

    @day_summary.calories_burnt = 0 if @current_index == 0

    @free_workout_exercises = @workout.workout_exercises #array
    @current_index = @free_workout_exercises.find_index(@free_workout_exercises.first)
    @current_freestyle_exercise = @free_workout_exercises[@current_index].exercise
    @max_index = @free_workout_exercises.count - 1

    @total_calories_burnt = @day_summary.calories_burnt
  end

  def stop
    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_by(date: Date.today)
    @total_calories = @workout_exercise.calories
    @duration = @workout_exercise.time.strftime("%M").to_f
    @calories_burnt_per_second = (@total_calories / @duration) / 60
    @total_calories_burnt = calculate_total_calories_burnt(@day_summary, @calories_burnt_per_second)
    @day_summary.update(end_time: Time.current, calories_burnt: @total_calories_burnt, status: "completed")

    @profile.user.total_kg_lifted_all

    redirect_to summary_workout_path(@workout_exercise.workout)

  end

  def update_last_time
    @profile = current_user.profile
    @day_summary = @profile.day_summaries.find_by(date: Date.today)
    @total_calories = @workout_exercise.calories
    @duration = @workout_exercise.time.strftime("%M").to_f
    @calories_burnt_per_second = (@total_calories / @duration) / 60
    if @day_summary.present?
      @total_calories_burnt = calculate_total_calories_burnt(@day_summary, @calories_burnt_per_second)
      @day_summary.update(last_update_time: Time.current, calories_burnt: @total_calories_burnt)
    end

    next_exercise_id = @workout_exercise.id.to_i + 1
    redirect_to workout_exercise_path(next_exercise_id)

  end

  private

  def set_workout_exercise
    @workout_exercise = WorkoutExercise.find(params[:id])
  end

  def calculate_total_calories_burnt(day_summary, calories_burnt_per_second)
    last_update_time = day_summary.last_update_time || day_summary.start_time
    elapsed_seconds = (Time.current - last_update_time).to_i

    accumulated_calories = day_summary.calories_burnt
    additional_calories = calories_burnt_per_second * elapsed_seconds

    total_calories_burnt = accumulated_calories + additional_calories
    day_summary.update(calories_burnt: total_calories_burnt, last_update_time: Time.current)

    total_calories_burnt
  end
end

app/views/workout_exercises/freestyle_show.html.erb
<div class="update-container d-flex justify-content-evenly mt-3" data-controller="update"
                                                                data-update-start-time="<%= @day_summary.start_time.iso8601 %>"
                                                                data-update-calories-burnt-per-second="<%= @calories_burnt_per_second %>"
                                                                data-update-total-calories-burnt="<%= @total_calories_burnt %>">
  <div class="update-item">
    <p class="mb-1">Calories</p>
    <span id="calories_burnt" data-update-target="caloriesBurnt"><%= @total_calories_burnt.round(2) %></span> kcals
  </div>
  <div class="update-item">
    <p class="mb-1">Time</p>
    <span id="timer" data-update-target="timer">00:00:00</span>
  </div>
</div>

<div class="exercise-instruction-show d-flex flex-column p-3">
  <h3 class="exercise-description-show my-3"><%= @current_freestyle_exercise.description %></h3>
  <%= image_tag @current_freestyle_exercise.image_url, style:"width:80%; margin:0 auto" %>
  <div class="exercise-info-show" style="margin-top: 30px">
    <p class="exercise-info-bold mb-0">💪 Activated Muscles:</p><p class="exercise-info-thin"> <%= @current_freestyle_exercise.muscle_group %></p>
    <p class="exercise-info-bold mb-0">📝 Instruction:</p><p class="exercise-info-thin"><%= @current_freestyle_exercise.instruction %></p>
  </div>
  <div class="exercise-buttons m-auto" data-controller="toggle-video">
    <%# <button> history </button> %>
    <button id="watch-button"data-toggle-video-target="watch" data-action="click->toggle-video#toggle"><i class="fa-solid fa-video" style="font-size: 12px; color: white;"></i></button>
    <div data-toggle-video-target="content" class="d-none">
      <iframe class="mt-1"style="width:95%; margin:0 auto;" src="<%= @current_freestyle_exercise.video_url %>" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
  </div>
</div>


<div class="button-container d-flex justify-content-between" style="width:80%; margin:0 auto; margin-top: 30px; margin-bottom:200px">
  <%#= link_to "EndWorkout", summary_workout_path(@workout), class: "btn btn-primary-custom" %>
  <%= button_to 'End', stop_workout_exercise_path(@workout_exercise), method: :patch, class: "sec-btn" %>
  <%= link_to "Skip", workout_exercise_path(@workout_exercise.id.to_i + 1), class: "sec-btn" %>
  <%# <button class="btn btn-success-custom" data-controller="next" data-next-url-value="<%= next_set_workout_exercise_path(@workout_exercise)%> <%#" data-action="click->next#next"> Complete this set</button> %>
  <% if @current_index < @max_index %>
    <%= button_to 'Next set', update_last_time_workout_exercise_path(@workout_exercise), method: :patch, class: "pri-btn", form: { data: { turbo: false } } %>
  <% else %>
    <%#= link_to "COMPLETED", summary_workout_path(@workout), class: "pri-btn" %>
    <%= button_to 'Complete', stop_workout_exercise_path(@workout_exercise), method: :patch, class: "pri-btn-complete" %>
  <% end %>
</div>

app/views/workout_exercises/show.html.erb
<div class="update-container d-flex justify-content-evenly mt-3" data-controller="update"
                                                                data-update-start-time="<%= @day_summary.start_time.iso8601 %>"
                                                                data-update-calories-burnt-per-second="<%= @calories_burnt_per_second %>"
                                                                data-update-total-calories-burnt="<%= @total_calories_burnt %>">
  <div class="update-item">
    <p class="mb-1">Calories</p>
    <span id="calories_burnt" data-update-target="caloriesBurnt"><%= @total_calories_burnt.round(2) %></span> kcals
  </div>
  <div class="update-item">
    <p class="mb-1">Time</p>
    <span id="timer" data-update-target="timer">00:00:00</span>
  </div>
</div>

<div class="exercise-instruction-show d-flex flex-column p-3">
  <h3 class="exercise-description-show my-3"><%= @current_exercise.description %></h3>
  <%= image_tag @current_exercise.image_url, style:"width:80%; margin:0 auto" %>
  <div class="exercise-info-show">
    <p class="exercise-info-bold mb-0">💪 Activated Muscles:</p><p class="exercise-info-thin"><%= @current_exercise.muscle_group %></p>
    <p class="exercise-info-bold mb-0">📝 Instruction:</p><p class="exercise-info-thin"><%= @current_exercise.instruction %></p>
  </div>
  <div class="watch-button-container" data-controller="toggle-video">
    <%# <button> history </button> %>
    <button id="watch-button" data-toggle-video-target="watch" data-action="click->toggle-video#toggle"><i class="fa-solid fa-video" style="font-size: 12px; color: white;"></i></button>
    <div data-toggle-video-target="content" class="d-none">
      <%# <p class="">hello</p> %>
      <%#= video_tag @current_exercise.video_url, class:"" %>
      <iframe class="mt-1"style="width:95%; margin:0 auto;" src="<%= @current_exercise.video_url %>" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
    </div>
  </div>
</div>

<div class="button-container d-flex justify-content-between" style="width:80%; margin:0 auto; margin-top: 30px; margin-bottom:200px">
  <%#= link_to "EndWorkout", summary_workout_path(@workout), class: "btn btn-primary-custom" %>
  <%= button_to 'End', stop_workout_exercise_path(@workout_exercise), method: :patch, class: "sec-btn" %>
  <%= link_to "Skip", workout_exercise_path(@workout_exercise.id.to_i + 1), class: "sec-btn" %>
  <%# <button class="btn btn-success-custom" data-controller="next" data-next-url-value="<%= next_set_workout_exercise_path(@workout_exercise)%> <%#" data-action="click->next#next"> Complete this set</button> %>
  <% if @current_index < @max_index %>
    <%= button_to 'Next set', update_last_time_workout_exercise_path(@workout_exercise), method: :patch, class: "pri-btn freestyle-next-set-btn", form: { data: { turbo: false } } %>
  <% else %>
    <%#= link_to "COMPLETED", summary_workout_path(@workout), class: "pri-btn" %>
    <%= button_to 'Complete', stop_workout_exercise_path(@workout_exercise), method: :patch, class: "pri-btn-complete freestyle-complete-set-btn" %>
  <% end %>
</div>