config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'events/create'
  get 'events/index'
  get 'events/show'
  root to: "profiles#edit"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events, only: [:index]

  resources :workouts, only: %i[index show create delete] do
    member do
      get 'overview'
      get 'description'
      get 'summary'
      post 'complete'
      patch 'start'
      patch 'freestyle_start'
      get 'freestyle'
      post 'add_exercise'
      delete 'remove_exercise'
    end
  end

  resources :workout_exercises, only: %i[show create] do
    member do
      post 'next_set'
      patch 'stop'
      patch 'update_last_time'
      get 'freestyle_show'
    end
  end

  resources :exercises, only: [:index, :show]

  resource :profile, only: %i[edit update show] do
    member do
    end
  end
  resources :group_classes, only: [:show]
  get 'home', to: 'pages#home', as: 'home'
end

app/views/shared/_bottom_bar.html.erb
<div data-controller="lightbox">
  <div class="bottom-bar rounded-pill" data-controller="popup">
    <div class="bar-content">
      <p class="bar-button ms-3">
        <%= link_to home_path, class: "text-decoration-none text-white", onclick: "window.location.href='#{home_path}'" do %>
          <i class="fa-solid fa-house" style="color: #ffffff;"></i>
        <% end %>
      </p>

      <p class="bar-button">
        <%= link_to "Choose Workout", workouts_path, id: "chooseWorkoutButton", class: "text-decoration-none text-white btn btn-link", data: { action: "click->lightbox#open" } %>
      </p>

      <p class="bar-button me-3">
        <% if current_page?(profile_path) %>
          <i class="fa-solid fa-bars three-bars" style="color: #ffffff" data-action="click->popup#toggleMenu"></i>
        <% else %>
          <%= link_to profile_path, class: "text-decoration-none text-white" do %>
            <i class="fa-solid fa-user" style="color: #ffffff;"></i>
          <% end %>
        <% end %>
      </p>
    </div>

    <div class="popup-wrapper">
      <% if current_page?(profile_path) %>
        <div class="popup-menu hidden" data-popup-target="menu">
          <ul>
            <li><a href="<%= root_path %>">Edit Profile</a></li>
            <li><%= link_to 'Log Off', destroy_user_session_path, data: { turbo_method: :delete, confirm: 'Are you sure?' } %></li>
          </ul>
        </div>
      <% end %>
    </div>
</div>

<div class="lightbox" data-lightbox-target="box">
  <div class="lightbox-content">
    <span data-action="click->lightbox#close" class="close">&times;</span>
    <h1>💪</h1>
    <h2>Choose Today's Program!</h2>
    <ul>
      <% @workouts.each do |workout| %>
        <li>
          <% if workout.name == 'Freestyle' %>
            <%= link_to workout_path(workout, from_freestyle: true), class: "workout-type-button" do %>
              <%= workout.name %>
            <% end %>
          <% else %>
            <%= link_to overview_workout_path(workout), class: "workout-type-button" do %>
              <%= workout.name %>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon", style="height:100px; position: relative;">
  <div class="container-fluid d-flex justify-content-center" style="position: absolute; bottom: 5px; width: 100%;">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag 'logo.jpg', alt: 'Logo', style: "height: 50px; width: auto;" %>
    <% end %>
  </div>
</div>