config/routes.rb
Rails.application.routes.draw do
  get 'events/new'
  get 'events/create'
  get 'events/index'
  get 'events/show'
  root to: "profiles#edit"

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :events, only: [:index]

  resources :workouts, only: %i[index show create delete] do
    member do
      get 'overview'
      get 'description'
      get 'summary'
      post 'complete'
      patch 'start'
      patch 'freestyle_start'
      get 'freestyle'
      post 'add_exercise'
      delete 'remove_exercise'
    end
  end

  resources :workout_exercises, only: %i[show create] do
    member do
      post 'next_set'
      patch 'stop'
      patch 'update_last_time'
      get 'freestyle_show'
    end
  end

  resources :exercises, only: [:index, :show]

  resource :profile, only: %i[edit update show] do
    member do
    end
  end
  resources :group_classes, only: [:show]
  get 'home', to: 'pages#home', as: 'home'
end

app/views/pages/home.html.erb
<%# #image box where it is writtne Weekly Hightlights%>
<div class="img-container">
  <div class="img-box d-flex justify-content-center">
    <%= image_tag @rand_img, alt: "Random Image", class:"rand-image rounded-5"%>
  </div>
  <div class="img-title">
    <h2 class="fs-1 title">Weekly<br>Highlights</h2>
  </div>
</div>

<%# #calendar of the month %>
<%= week_calendar do |date| %>
  <%= date %>
<% end %>

<div class="daily-summary d-none">
  <p class="mb-0 fs-6">
    💪 Workout Type : “Strength Training”<br>
    ⏳ Duration : 45 mins<br>
    🔥 Calories Burnt : 350 kcal
  </p>
</div>

<%# #Activities list %>
<div class="activity-list">
  <div class="d-flex justify-content-between">
    <h2 class="title" id="title-activity">Activities</h2>
    <%# <%= link_to "see all >", exercises_path, class:"see-all" %>
    <%# <p class="see-all">link_to "see all >", exercises_path</p> %>
  </div>
  <div class="d-flex justify-content-between activity-container">
    <% @type_workout.each do |type| %>
      <% if type.name == "Freestyle" %>
      <% else %>
        <div class="activity-wrapper" data-controller="activity">
          <div class="activity-box" style="width:67px;">
            <div class="activity-category ms-0">
              <div class="d-flex flex-column justify-content-center align-items-center activity-hover-box">
                <button class="activity-item" data-action="click->activity#open"><%= raw type.icon %></button>
                <p class="activity-type-name"> <%= type.name %> </p>
              </div>
            </div>
          </div>
          <!-- Pop up for activities -->
          <div class="activity-popup" data-activity-target="type">
            <div class="activity-popup-content">
              <span data-action="click->activity#close" class="close">&times;</span>
              <div class="activity-popup-text-box">
                <p class="activity-popup-title"><%= type.name %></p>
                <ul class="activity-popup-exercise-list p-0">
                  <% type.exercises.each do |exercise| %>
                    <%# <li class="activity-popup-exercise"><%= exercise.name %>
                    <li class="activity-popup-exercise"><%= link_to exercise.name, exercise_path(exercise), class:"exercise-name-popup" %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%# #Class for you title with class cards %>
<div class="group-class-index">
  <h2 class="title" id="title-group-classes">Class for you</h2>
  <% if @groupe_classes.present? %>  <%# Check if @groupe_classes is not nil or empty %>
    <% @groupe_classes.each do |group_class| %>
      <%= link_to group_class_path(group_class), class: "group-class-card-link text-decoration-none text-dark" do %>
        <div class="group-class-card d-flex px-4 py-2">
          <div class="group-class-image p-3">
            <%= image_tag group_class.image_url, alt: "GroupClass Image", class: "group-class-img" %>
          </div>
          <div class="card-info flex-grow-1" style="height:100px; margin-left:20px">
            <div class="card-letters pt-1 d-flex flex-column justify-content-between ">
              <p class="mb-3 fs-5"><%= group_class.name %></p>
              <p class="pt-4 mb-0"><%= group_class.time.strftime('%H:%M') %>, <%= group_class.date.day %>/<%= group_class.date.month %> (<%= group_class.date.strftime("%a") %>)</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <p>No upcoming classes.</p>
  <% end %>
</div>